# Generated by Django 3.1.3 on 2021-01-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=50, unique=True, verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.SlugField(unique=True, verbose_name='Образец')),
                ('date_production', models.DateField(auto_now=True, db_index=True, verbose_name='Дата производства')),
                ('bb_for_i', models.IntegerField(blank=True, null=True, verbose_name='Б/Б с')),
                ('bb_and_for', models.IntegerField(blank=True, null=True, verbose_name='Б/Б по')),
                ('pallet_for_i', models.IntegerField(blank=True, null=True, verbose_name='паллеты с')),
                ('pallet_and_for', models.IntegerField(blank=True, null=True, verbose_name='паллеты по')),
                ('repeate', models.BooleanField(verbose_name='повтор')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Дата анализа')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('category', models.ManyToManyField(blank=True, related_name='samples', to='main.Category', verbose_name='категория')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='компания')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'образец',
                'verbose_name_plural': 'образцы',
            },
        ),
        migrations.CreateModel(
            name='Fat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat_blank_cup', models.FloatField(blank=True, null=True, verbose_name='масса пустого стакана')),
                ('fat_sample_mass', models.FloatField(blank=True, null=True, verbose_name='масса навески')),
                ('fat_final_cup_mass', models.FloatField(blank=True, null=True, verbose_name='масса стакана i')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='массовая доля сырого жира')),
                ('date_pub', models.DateTimeField(auto_now=True, verbose_name='дата анализа')),
                ('samples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fats', to='main.sample')),
            ],
            options={
                'verbose_name': 'жир',
                'verbose_name_plural': 'жир',
            },
        ),
    ]
